TRAINING_PHRASES = [
    "Absolutely not.",
    "I think not.",
    "Not a chance.",
    "No way, Jose.",
    "Not in a million years.",
    "I'm afraid that won't be possible.",
    "That's a hard pass from me.",
    "Not today, Satan.",
    "I'll have to decline.",
    "That's not going to happen.",
    "Not on my watch.",
    "I don't think so.",
    "Fat chance.",
    "Dream on.",
    "When pigs fly.",
    "Over my dead body.",
    "Not if I can help it.",
    "I'm going to have to say no.",
    "That's not in the cards.",
    "I'm not feeling it.",
    "Not my cup of tea.",
    "I'll pass, thanks.",
    "That's off the table.",
    "Not happening.",
    "I'm drawing the line here.",
    "That's where I stop.",
    "Count me out.",
    "I'm not on board with that.",
    "That's not my jam.",
    "I'm going to sit this one out.",
    "Not in this lifetime.",
    "I must respectfully decline.",
    "That's not within my comfort zone.",
    "I'm afraid I can't accommodate that.",
    "That doesn't align with my values.",
    "I'm not available for that.",
    "That's not something I can support.",
    "I'll have to take a rain check.",
    "That's not my forte.",
    "I'm not equipped for that.",
    "That's outside my wheelhouse.",
    "I'm not the right person for this.",
    "That doesn't work for me.",
    "I'm going to have to bow out.",
    "That's not feasible.",
    "I can't make that commitment.",
    "That's not realistic for me.",
    "I don't have the bandwidth for that.",
    "That's not on my agenda.",
    "I'm stretched too thin already.",
    "That's not a priority right now.",
    "Nope, not gonna happen.",
    "Negative, ghostrider.",
    "Computer says no.",
    "Error 404: Interest not found.",
    "I'm allergic to that idea.",
    "My magic 8-ball says no.",
    "The universe is conspiring against it.",
    "My horoscope advised against it.",
    "The stars are not aligned for this.",
    "I consulted my crystal ball and it said no.",
    "My gut feeling is strongly opposed.",
    "The force is not with this one.",
    "I'm getting bad vibes from that.",
    "My inner wisdom says to decline.",
    "That goes against my feng shui.",
    "I'd rather eat glass.",
    "I'd rather watch paint dry.",
    "I'd prefer a root canal.",
    "I'd rather count grains of sand.",
    "I'd sooner learn ancient Sumerian.",
    "I'd rather debug assembly code.",
    "That's about as appealing as a soggy sandwich.",
    "I'd rather solve a Rubik's cube blindfolded.",
    "That sounds worse than stepping on a LEGO.",
    "I'd prefer to watch cricket in slow motion.",
    "No can do, buckaroo.",
    "Nah, I'm good.",
    "Thanks, but no thanks.",
    "I appreciate the offer, but no.",
    "That's kind of you, but I'll pass.",
    "I'm flattered, but no.",
    "I'm honored by the suggestion, but no.",
    "While I appreciate the thought, I must decline.",
    "That's generous of you, but I can't accept.",
    "I'm touched by the offer, but no.",
    "How thoughtful, but I'll have to say no.",
    "Sorry, that's not going to work.",
    "I wish I could, but I can't.",
    "Unfortunately, that's not possible.",
    "Regrettably, I must decline.",
    "I'm sorry, but that's not an option.",
    "Much as I'd like to, I can't.",
    "I'm afraid that's out of the question.",
    "Sadly, that won't be happening.",
    "I hate to disappoint, but no.",
    "It pains me to say this, but no.",
]